services:
  webapp:               # nginx unit
    build:
      dockerfile: webapp.Dockerfile
    ports:
      - "8080:8000"     # web server port
    volumes:
      - ./config:/docker-entrypoint.d
      - ./web:/web:ro
      - ./service:/service:ro
    depends_on:
      db:
        condition:
          service_healthy
  db:                   # neo4j graph database
    image:  "neo4j"     # use the neo4j image from docker hub
    ports:
      # These ports are only exposed to the host machine for testing purposes.
      # For production, they should only be exposed internally to the other services
      - "7474:7474"     # HTTP
      - "7473:7473"     # HTTPS
      - "7687:7687"     # Bolt
    volumes:
      - ./db/conf:/conf
      - ./db/data:/data
      - ./db/import:/import
      - ./db/licenses:/licenses
      - ./db/logs:/logs
      - ./db/plugins:/plugins
      - ./db/ssl:/ssl
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
