name: Deploy to AWS

on:
    workflow_dispatch: {}
    push:
        branches:
            - 'prod'
        paths-ignore:
            - 'tf/**'
            - '.gitignore'
            - 'README.md'

env:
    AWS_REGION: us-east-2

jobs:
    deploy:
        name: CodeDeploy Deployment
        runs-on: ubuntu-latest
        environment: Production
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Confirm commit SHA
              run: echo "Latest commit sha is ${{ github.sha }}"

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                role-to-assume: arn:aws:iam::445567081553:role/GitHubCodeDeployRole
                aws-region: ${{ env.AWS_REGION }}

            - name: Create CodeDeploy Deployment
              run: |
                echo "Deploying commit ${{ github.sha }} from ${{ github.repository }} to AWS"
                aws deploy create-deployment --application-name GopherMaps --deployment-group-name GopherMaps-DG --github-location repository=${{ github.repository }},commitid=${{ github.sha }} --ignore-application-stop-failures

